# Generated by Django 4.0.3 on 2022-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField()),
                ('employeeName', models.CharField(max_length=60)),
                ('employeeClass', models.CharField(max_length=20)),
                ('employeeSection', models.CharField(max_length=20)),
                ('employeeCity', models.CharField(default='NA', max_length=20)),
            ],
        ),
    ]
